name: Integration Tests

on:
  push:
    branches:
      - master

  pull_request_target:
    branches:
    - master

jobs:
  tests-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: make tests-intergration
  tests-arm64:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: make tests-intergration
